//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishSchoolManagerModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escola
    {
        public Escola()
        {
            this.Aulas = new HashSet<Aula>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public bool Ativo { get; set; }
    
        public virtual ICollection<Aula> Aulas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
