//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EnglishSchoolManagerModel", "FK__tblUsuari__AulaI__32E0915F", "Aula", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EnglishSchoolManagerModel.Aula), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnglishSchoolManagerModel.Usuario), true)]
[assembly: EdmRelationshipAttribute("EnglishSchoolManagerModel", "FK__tblAula__EscolaI__4AB81AF0", "tblEscola", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnglishSchoolManagerModel.Escola), "Aula", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnglishSchoolManagerModel.Aula), true)]
[assembly: EdmRelationshipAttribute("EnglishSchoolManagerModel", "FK__tblUsuari__Escol__49C3F6B7", "tblEscola", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnglishSchoolManagerModel.Escola), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnglishSchoolManagerModel.Usuario), true)]
[assembly: EdmRelationshipAttribute("EnglishSchoolManagerModel", "FK__tblPagame__Escol__4AB81AF0", "Escola", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnglishSchoolManagerModel.Escola), "tblPagamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnglishSchoolManagerModel.Pagamento), true)]
[assembly: EdmRelationshipAttribute("EnglishSchoolManagerModel", "FK__tblPagame__Aluno__49C3F6B7", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EnglishSchoolManagerModel.Usuario), "tblPagamento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EnglishSchoolManagerModel.Pagamento), true)]

#endregion

namespace EnglishSchoolManagerModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ESMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ESMEntities object using the connection string found in the 'ESMEntities' section of the application configuration file.
        /// </summary>
        public ESMEntities() : base("name=ESMEntities", "ESMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ESMEntities object.
        /// </summary>
        public ESMEntities(string connectionString) : base(connectionString, "ESMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ESMEntities object.
        /// </summary>
        public ESMEntities(EntityConnection connection) : base(connection, "ESMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aula> Aulas
        {
            get
            {
                if ((_Aulas == null))
                {
                    _Aulas = base.CreateObjectSet<Aula>("Aulas");
                }
                return _Aulas;
            }
        }
        private ObjectSet<Aula> _Aulas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Escola> Escolas
        {
            get
            {
                if ((_Escolas == null))
                {
                    _Escolas = base.CreateObjectSet<Escola>("Escolas");
                }
                return _Escolas;
            }
        }
        private ObjectSet<Escola> _Escolas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pagamento> Pagamentos
        {
            get
            {
                if ((_Pagamentos == null))
                {
                    _Pagamentos = base.CreateObjectSet<Pagamento>("Pagamentos");
                }
                return _Pagamentos;
            }
        }
        private ObjectSet<Pagamento> _Pagamentos;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Aulas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAulas(Aula aula)
        {
            base.AddObject("Aulas", aula);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Escolas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEscolas(Escola escola)
        {
            base.AddObject("Escolas", escola);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pagamentos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPagamentos(Pagamento pagamento)
        {
            base.AddObject("Pagamentos", pagamento);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnglishSchoolManagerModel", Name="Aula")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Aula : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Aula object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="particular">Initial value of the Particular property.</param>
        /// <param name="usuarioInsercaoId">Initial value of the UsuarioInsercaoId property.</param>
        /// <param name="usuarioAlteracaoId">Initial value of the UsuarioAlteracaoId property.</param>
        /// <param name="dataInsercao">Initial value of the DataInsercao property.</param>
        /// <param name="dataAlteracao">Initial value of the DataAlteracao property.</param>
        /// <param name="valorMensalidade">Initial value of the ValorMensalidade property.</param>
        /// <param name="escolaId">Initial value of the EscolaId property.</param>
        public static Aula CreateAula(global::System.Int32 id, global::System.Boolean particular, global::System.Int32 usuarioInsercaoId, global::System.Int32 usuarioAlteracaoId, global::System.DateTime dataInsercao, global::System.DateTime dataAlteracao, global::System.Decimal valorMensalidade, global::System.Int32 escolaId)
        {
            Aula aula = new Aula();
            aula.Id = id;
            aula.Particular = particular;
            aula.UsuarioInsercaoId = usuarioInsercaoId;
            aula.UsuarioAlteracaoId = usuarioAlteracaoId;
            aula.DataInsercao = dataInsercao;
            aula.DataAlteracao = dataAlteracao;
            aula.ValorMensalidade = valorMensalidade;
            aula.EscolaId = escolaId;
            return aula;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true, "Descricao");
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HorariosJson
        {
            get
            {
                return _HorariosJson;
            }
            set
            {
                OnHorariosJsonChanging(value);
                ReportPropertyChanging("HorariosJson");
                _HorariosJson = StructuralObject.SetValidValue(value, true, "HorariosJson");
                ReportPropertyChanged("HorariosJson");
                OnHorariosJsonChanged();
            }
        }
        private global::System.String _HorariosJson;
        partial void OnHorariosJsonChanging(global::System.String value);
        partial void OnHorariosJsonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Particular
        {
            get
            {
                return _Particular;
            }
            set
            {
                OnParticularChanging(value);
                ReportPropertyChanging("Particular");
                _Particular = StructuralObject.SetValidValue(value, "Particular");
                ReportPropertyChanged("Particular");
                OnParticularChanged();
            }
        }
        private global::System.Boolean _Particular;
        partial void OnParticularChanging(global::System.Boolean value);
        partial void OnParticularChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioInsercaoId
        {
            get
            {
                return _UsuarioInsercaoId;
            }
            set
            {
                OnUsuarioInsercaoIdChanging(value);
                ReportPropertyChanging("UsuarioInsercaoId");
                _UsuarioInsercaoId = StructuralObject.SetValidValue(value, "UsuarioInsercaoId");
                ReportPropertyChanged("UsuarioInsercaoId");
                OnUsuarioInsercaoIdChanged();
            }
        }
        private global::System.Int32 _UsuarioInsercaoId;
        partial void OnUsuarioInsercaoIdChanging(global::System.Int32 value);
        partial void OnUsuarioInsercaoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioAlteracaoId
        {
            get
            {
                return _UsuarioAlteracaoId;
            }
            set
            {
                OnUsuarioAlteracaoIdChanging(value);
                ReportPropertyChanging("UsuarioAlteracaoId");
                _UsuarioAlteracaoId = StructuralObject.SetValidValue(value, "UsuarioAlteracaoId");
                ReportPropertyChanged("UsuarioAlteracaoId");
                OnUsuarioAlteracaoIdChanged();
            }
        }
        private global::System.Int32 _UsuarioAlteracaoId;
        partial void OnUsuarioAlteracaoIdChanging(global::System.Int32 value);
        partial void OnUsuarioAlteracaoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInsercao
        {
            get
            {
                return _DataInsercao;
            }
            set
            {
                OnDataInsercaoChanging(value);
                ReportPropertyChanging("DataInsercao");
                _DataInsercao = StructuralObject.SetValidValue(value, "DataInsercao");
                ReportPropertyChanged("DataInsercao");
                OnDataInsercaoChanged();
            }
        }
        private global::System.DateTime _DataInsercao;
        partial void OnDataInsercaoChanging(global::System.DateTime value);
        partial void OnDataInsercaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAlteracao
        {
            get
            {
                return _DataAlteracao;
            }
            set
            {
                OnDataAlteracaoChanging(value);
                ReportPropertyChanging("DataAlteracao");
                _DataAlteracao = StructuralObject.SetValidValue(value, "DataAlteracao");
                ReportPropertyChanged("DataAlteracao");
                OnDataAlteracaoChanged();
            }
        }
        private global::System.DateTime _DataAlteracao;
        partial void OnDataAlteracaoChanging(global::System.DateTime value);
        partial void OnDataAlteracaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ValorMensalidade
        {
            get
            {
                return _ValorMensalidade;
            }
            set
            {
                OnValorMensalidadeChanging(value);
                ReportPropertyChanging("ValorMensalidade");
                _ValorMensalidade = StructuralObject.SetValidValue(value, "ValorMensalidade");
                ReportPropertyChanged("ValorMensalidade");
                OnValorMensalidadeChanged();
            }
        }
        private global::System.Decimal _ValorMensalidade;
        partial void OnValorMensalidadeChanging(global::System.Decimal value);
        partial void OnValorMensalidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EscolaId
        {
            get
            {
                return _EscolaId;
            }
            set
            {
                OnEscolaIdChanging(value);
                ReportPropertyChanging("EscolaId");
                _EscolaId = StructuralObject.SetValidValue(value, "EscolaId");
                ReportPropertyChanged("EscolaId");
                OnEscolaIdChanged();
            }
        }
        private global::System.Int32 _EscolaId;
        partial void OnEscolaIdChanging(global::System.Int32 value);
        partial void OnEscolaIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblUsuari__AulaI__32E0915F", "Usuario")]
        public EntityCollection<Usuario> Alunos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("EnglishSchoolManagerModel.FK__tblUsuari__AulaI__32E0915F", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("EnglishSchoolManagerModel.FK__tblUsuari__AulaI__32E0915F", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblAula__EscolaI__4AB81AF0", "tblEscola")]
        public Escola Escola
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblAula__EscolaI__4AB81AF0", "tblEscola").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblAula__EscolaI__4AB81AF0", "tblEscola").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Escola> EscolaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblAula__EscolaI__4AB81AF0", "tblEscola");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblAula__EscolaI__4AB81AF0", "tblEscola", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnglishSchoolManagerModel", Name="Escola")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Escola : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Escola object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        public static Escola CreateEscola(global::System.Int32 id, global::System.String nome, global::System.Boolean ativo)
        {
            Escola escola = new Escola();
            escola.Id = id;
            escola.Nome = nome;
            escola.Ativo = ativo;
            return escola;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value, "Ativo");
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblAula__EscolaI__4AB81AF0", "Aula")]
        public EntityCollection<Aula> Aulas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Aula>("EnglishSchoolManagerModel.FK__tblAula__EscolaI__4AB81AF0", "Aula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Aula>("EnglishSchoolManagerModel.FK__tblAula__EscolaI__4AB81AF0", "Aula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblUsuari__Escol__49C3F6B7", "Usuario")]
        public EntityCollection<Usuario> Usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("EnglishSchoolManagerModel.FK__tblUsuari__Escol__49C3F6B7", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("EnglishSchoolManagerModel.FK__tblUsuari__Escol__49C3F6B7", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblPagame__Escol__4AB81AF0", "tblPagamento")]
        public EntityCollection<Pagamento> Pagamentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pagamento>("EnglishSchoolManagerModel.FK__tblPagame__Escol__4AB81AF0", "tblPagamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pagamento>("EnglishSchoolManagerModel.FK__tblPagame__Escol__4AB81AF0", "tblPagamento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnglishSchoolManagerModel", Name="Pagamento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pagamento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pagamento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="alunoId">Initial value of the AlunoId property.</param>
        /// <param name="escolaId">Initial value of the EscolaId property.</param>
        /// <param name="valor">Initial value of the Valor property.</param>
        /// <param name="pagamentoEfetuado">Initial value of the PagamentoEfetuado property.</param>
        /// <param name="usuarioInsercaoId">Initial value of the UsuarioInsercaoId property.</param>
        /// <param name="usuarioAlteracaoId">Initial value of the UsuarioAlteracaoId property.</param>
        /// <param name="dataInsercao">Initial value of the DataInsercao property.</param>
        /// <param name="dataAlteracao">Initial value of the DataAlteracao property.</param>
        public static Pagamento CreatePagamento(global::System.Int32 id, global::System.Int32 alunoId, global::System.Int32 escolaId, global::System.Decimal valor, global::System.Boolean pagamentoEfetuado, global::System.Int32 usuarioInsercaoId, global::System.Int32 usuarioAlteracaoId, global::System.DateTime dataInsercao, global::System.DateTime dataAlteracao)
        {
            Pagamento pagamento = new Pagamento();
            pagamento.Id = id;
            pagamento.AlunoId = alunoId;
            pagamento.EscolaId = escolaId;
            pagamento.Valor = valor;
            pagamento.PagamentoEfetuado = pagamentoEfetuado;
            pagamento.UsuarioInsercaoId = usuarioInsercaoId;
            pagamento.UsuarioAlteracaoId = usuarioAlteracaoId;
            pagamento.DataInsercao = dataInsercao;
            pagamento.DataAlteracao = dataAlteracao;
            return pagamento;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AlunoId
        {
            get
            {
                return _AlunoId;
            }
            set
            {
                OnAlunoIdChanging(value);
                ReportPropertyChanging("AlunoId");
                _AlunoId = StructuralObject.SetValidValue(value, "AlunoId");
                ReportPropertyChanged("AlunoId");
                OnAlunoIdChanged();
            }
        }
        private global::System.Int32 _AlunoId;
        partial void OnAlunoIdChanging(global::System.Int32 value);
        partial void OnAlunoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EscolaId
        {
            get
            {
                return _EscolaId;
            }
            set
            {
                OnEscolaIdChanging(value);
                ReportPropertyChanging("EscolaId");
                _EscolaId = StructuralObject.SetValidValue(value, "EscolaId");
                ReportPropertyChanged("EscolaId");
                OnEscolaIdChanged();
            }
        }
        private global::System.Int32 _EscolaId;
        partial void OnEscolaIdChanging(global::System.Int32 value);
        partial void OnEscolaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Valor
        {
            get
            {
                return _Valor;
            }
            set
            {
                OnValorChanging(value);
                ReportPropertyChanging("Valor");
                _Valor = StructuralObject.SetValidValue(value, "Valor");
                ReportPropertyChanged("Valor");
                OnValorChanged();
            }
        }
        private global::System.Decimal _Valor;
        partial void OnValorChanging(global::System.Decimal value);
        partial void OnValorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PagamentoEfetuado
        {
            get
            {
                return _PagamentoEfetuado;
            }
            set
            {
                OnPagamentoEfetuadoChanging(value);
                ReportPropertyChanging("PagamentoEfetuado");
                _PagamentoEfetuado = StructuralObject.SetValidValue(value, "PagamentoEfetuado");
                ReportPropertyChanged("PagamentoEfetuado");
                OnPagamentoEfetuadoChanged();
            }
        }
        private global::System.Boolean _PagamentoEfetuado;
        partial void OnPagamentoEfetuadoChanging(global::System.Boolean value);
        partial void OnPagamentoEfetuadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataPagamento
        {
            get
            {
                return _DataPagamento;
            }
            set
            {
                OnDataPagamentoChanging(value);
                ReportPropertyChanging("DataPagamento");
                _DataPagamento = StructuralObject.SetValidValue(value, "DataPagamento");
                ReportPropertyChanged("DataPagamento");
                OnDataPagamentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataPagamento;
        partial void OnDataPagamentoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataPagamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioInsercaoId
        {
            get
            {
                return _UsuarioInsercaoId;
            }
            set
            {
                OnUsuarioInsercaoIdChanging(value);
                ReportPropertyChanging("UsuarioInsercaoId");
                _UsuarioInsercaoId = StructuralObject.SetValidValue(value, "UsuarioInsercaoId");
                ReportPropertyChanged("UsuarioInsercaoId");
                OnUsuarioInsercaoIdChanged();
            }
        }
        private global::System.Int32 _UsuarioInsercaoId;
        partial void OnUsuarioInsercaoIdChanging(global::System.Int32 value);
        partial void OnUsuarioInsercaoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioAlteracaoId
        {
            get
            {
                return _UsuarioAlteracaoId;
            }
            set
            {
                OnUsuarioAlteracaoIdChanging(value);
                ReportPropertyChanging("UsuarioAlteracaoId");
                _UsuarioAlteracaoId = StructuralObject.SetValidValue(value, "UsuarioAlteracaoId");
                ReportPropertyChanged("UsuarioAlteracaoId");
                OnUsuarioAlteracaoIdChanged();
            }
        }
        private global::System.Int32 _UsuarioAlteracaoId;
        partial void OnUsuarioAlteracaoIdChanging(global::System.Int32 value);
        partial void OnUsuarioAlteracaoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInsercao
        {
            get
            {
                return _DataInsercao;
            }
            set
            {
                OnDataInsercaoChanging(value);
                ReportPropertyChanging("DataInsercao");
                _DataInsercao = StructuralObject.SetValidValue(value, "DataInsercao");
                ReportPropertyChanged("DataInsercao");
                OnDataInsercaoChanged();
            }
        }
        private global::System.DateTime _DataInsercao;
        partial void OnDataInsercaoChanging(global::System.DateTime value);
        partial void OnDataInsercaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAlteracao
        {
            get
            {
                return _DataAlteracao;
            }
            set
            {
                OnDataAlteracaoChanging(value);
                ReportPropertyChanging("DataAlteracao");
                _DataAlteracao = StructuralObject.SetValidValue(value, "DataAlteracao");
                ReportPropertyChanged("DataAlteracao");
                OnDataAlteracaoChanged();
            }
        }
        private global::System.DateTime _DataAlteracao;
        partial void OnDataAlteracaoChanging(global::System.DateTime value);
        partial void OnDataAlteracaoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblPagame__Escol__4AB81AF0", "Escola")]
        public Escola Escola
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblPagame__Escol__4AB81AF0", "Escola").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblPagame__Escol__4AB81AF0", "Escola").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Escola> EscolaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblPagame__Escol__4AB81AF0", "Escola");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblPagame__Escol__4AB81AF0", "Escola", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblPagame__Aluno__49C3F6B7", "Usuario")]
        public Usuario Aluno
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("EnglishSchoolManagerModel.FK__tblPagame__Aluno__49C3F6B7", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("EnglishSchoolManagerModel.FK__tblPagame__Aluno__49C3F6B7", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> AlunoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("EnglishSchoolManagerModel.FK__tblPagame__Aluno__49C3F6B7", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("EnglishSchoolManagerModel.FK__tblPagame__Aluno__49C3F6B7", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EnglishSchoolManagerModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="nivelAcesso">Initial value of the NivelAcesso property.</param>
        /// <param name="usuarioInsercaoId">Initial value of the UsuarioInsercaoId property.</param>
        /// <param name="usuarioAlteracaoId">Initial value of the UsuarioAlteracaoId property.</param>
        /// <param name="dataInsercao">Initial value of the DataInsercao property.</param>
        /// <param name="dataAlteracao">Initial value of the DataAlteracao property.</param>
        /// <param name="ativo">Initial value of the Ativo property.</param>
        /// <param name="escolaId">Initial value of the EscolaId property.</param>
        /// <param name="valorMensalidade">Initial value of the ValorMensalidade property.</param>
        /// <param name="valorPersonalizado">Initial value of the ValorPersonalizado property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String email, global::System.String senha, global::System.Int32 nivelAcesso, global::System.Int32 usuarioInsercaoId, global::System.Int32 usuarioAlteracaoId, global::System.DateTime dataInsercao, global::System.DateTime dataAlteracao, global::System.Boolean ativo, global::System.Int32 escolaId, global::System.Decimal valorMensalidade, global::System.Boolean valorPersonalizado)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Nome = nome;
            usuario.Email = email;
            usuario.Senha = senha;
            usuario.NivelAcesso = nivelAcesso;
            usuario.UsuarioInsercaoId = usuarioInsercaoId;
            usuario.UsuarioAlteracaoId = usuarioAlteracaoId;
            usuario.DataInsercao = dataInsercao;
            usuario.DataAlteracao = dataAlteracao;
            usuario.Ativo = ativo;
            usuario.EscolaId = escolaId;
            usuario.ValorMensalidade = valorMensalidade;
            usuario.ValorPersonalizado = valorPersonalizado;
            return usuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false, "Senha");
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NivelAcesso
        {
            get
            {
                return _NivelAcesso;
            }
            set
            {
                OnNivelAcessoChanging(value);
                ReportPropertyChanging("NivelAcesso");
                _NivelAcesso = StructuralObject.SetValidValue(value, "NivelAcesso");
                ReportPropertyChanged("NivelAcesso");
                OnNivelAcessoChanged();
            }
        }
        private global::System.Int32 _NivelAcesso;
        partial void OnNivelAcessoChanging(global::System.Int32 value);
        partial void OnNivelAcessoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioInsercaoId
        {
            get
            {
                return _UsuarioInsercaoId;
            }
            set
            {
                OnUsuarioInsercaoIdChanging(value);
                ReportPropertyChanging("UsuarioInsercaoId");
                _UsuarioInsercaoId = StructuralObject.SetValidValue(value, "UsuarioInsercaoId");
                ReportPropertyChanged("UsuarioInsercaoId");
                OnUsuarioInsercaoIdChanged();
            }
        }
        private global::System.Int32 _UsuarioInsercaoId;
        partial void OnUsuarioInsercaoIdChanging(global::System.Int32 value);
        partial void OnUsuarioInsercaoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioAlteracaoId
        {
            get
            {
                return _UsuarioAlteracaoId;
            }
            set
            {
                OnUsuarioAlteracaoIdChanging(value);
                ReportPropertyChanging("UsuarioAlteracaoId");
                _UsuarioAlteracaoId = StructuralObject.SetValidValue(value, "UsuarioAlteracaoId");
                ReportPropertyChanged("UsuarioAlteracaoId");
                OnUsuarioAlteracaoIdChanged();
            }
        }
        private global::System.Int32 _UsuarioAlteracaoId;
        partial void OnUsuarioAlteracaoIdChanging(global::System.Int32 value);
        partial void OnUsuarioAlteracaoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInsercao
        {
            get
            {
                return _DataInsercao;
            }
            set
            {
                OnDataInsercaoChanging(value);
                ReportPropertyChanging("DataInsercao");
                _DataInsercao = StructuralObject.SetValidValue(value, "DataInsercao");
                ReportPropertyChanged("DataInsercao");
                OnDataInsercaoChanged();
            }
        }
        private global::System.DateTime _DataInsercao;
        partial void OnDataInsercaoChanging(global::System.DateTime value);
        partial void OnDataInsercaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataAlteracao
        {
            get
            {
                return _DataAlteracao;
            }
            set
            {
                OnDataAlteracaoChanging(value);
                ReportPropertyChanging("DataAlteracao");
                _DataAlteracao = StructuralObject.SetValidValue(value, "DataAlteracao");
                ReportPropertyChanged("DataAlteracao");
                OnDataAlteracaoChanged();
            }
        }
        private global::System.DateTime _DataAlteracao;
        partial void OnDataAlteracaoChanging(global::System.DateTime value);
        partial void OnDataAlteracaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefone
        {
            get
            {
                return _Telefone;
            }
            set
            {
                OnTelefoneChanging(value);
                ReportPropertyChanging("Telefone");
                _Telefone = StructuralObject.SetValidValue(value, true, "Telefone");
                ReportPropertyChanged("Telefone");
                OnTelefoneChanged();
            }
        }
        private global::System.String _Telefone;
        partial void OnTelefoneChanging(global::System.String value);
        partial void OnTelefoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Ativo
        {
            get
            {
                return _Ativo;
            }
            set
            {
                OnAtivoChanging(value);
                ReportPropertyChanging("Ativo");
                _Ativo = StructuralObject.SetValidValue(value, "Ativo");
                ReportPropertyChanged("Ativo");
                OnAtivoChanged();
            }
        }
        private global::System.Boolean _Ativo;
        partial void OnAtivoChanging(global::System.Boolean value);
        partial void OnAtivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AulaId
        {
            get
            {
                return _AulaId;
            }
            set
            {
                OnAulaIdChanging(value);
                ReportPropertyChanging("AulaId");
                _AulaId = StructuralObject.SetValidValue(value, "AulaId");
                ReportPropertyChanged("AulaId");
                OnAulaIdChanged();
            }
        }
        private Nullable<global::System.Int32> _AulaId;
        partial void OnAulaIdChanging(Nullable<global::System.Int32> value);
        partial void OnAulaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EscolaId
        {
            get
            {
                return _EscolaId;
            }
            set
            {
                OnEscolaIdChanging(value);
                ReportPropertyChanging("EscolaId");
                _EscolaId = StructuralObject.SetValidValue(value, "EscolaId");
                ReportPropertyChanged("EscolaId");
                OnEscolaIdChanged();
            }
        }
        private global::System.Int32 _EscolaId;
        partial void OnEscolaIdChanging(global::System.Int32 value);
        partial void OnEscolaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ValorMensalidade
        {
            get
            {
                return _ValorMensalidade;
            }
            set
            {
                OnValorMensalidadeChanging(value);
                ReportPropertyChanging("ValorMensalidade");
                _ValorMensalidade = StructuralObject.SetValidValue(value, "ValorMensalidade");
                ReportPropertyChanged("ValorMensalidade");
                OnValorMensalidadeChanged();
            }
        }
        private global::System.Decimal _ValorMensalidade;
        partial void OnValorMensalidadeChanging(global::System.Decimal value);
        partial void OnValorMensalidadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean ValorPersonalizado
        {
            get
            {
                return _ValorPersonalizado;
            }
            set
            {
                OnValorPersonalizadoChanging(value);
                ReportPropertyChanging("ValorPersonalizado");
                _ValorPersonalizado = StructuralObject.SetValidValue(value, "ValorPersonalizado");
                ReportPropertyChanged("ValorPersonalizado");
                OnValorPersonalizadoChanged();
            }
        }
        private global::System.Boolean _ValorPersonalizado;
        partial void OnValorPersonalizadoChanging(global::System.Boolean value);
        partial void OnValorPersonalizadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataProximoPagamento
        {
            get
            {
                return _DataProximoPagamento;
            }
            set
            {
                OnDataProximoPagamentoChanging(value);
                ReportPropertyChanging("DataProximoPagamento");
                _DataProximoPagamento = StructuralObject.SetValidValue(value, "DataProximoPagamento");
                ReportPropertyChanged("DataProximoPagamento");
                OnDataProximoPagamentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataProximoPagamento;
        partial void OnDataProximoPagamentoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataProximoPagamentoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblUsuari__AulaI__32E0915F", "Aula")]
        public Aula Aula
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aula>("EnglishSchoolManagerModel.FK__tblUsuari__AulaI__32E0915F", "Aula").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aula>("EnglishSchoolManagerModel.FK__tblUsuari__AulaI__32E0915F", "Aula").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Aula> AulaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Aula>("EnglishSchoolManagerModel.FK__tblUsuari__AulaI__32E0915F", "Aula");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Aula>("EnglishSchoolManagerModel.FK__tblUsuari__AulaI__32E0915F", "Aula", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblUsuari__Escol__49C3F6B7", "tblEscola")]
        public Escola Escola
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblUsuari__Escol__49C3F6B7", "tblEscola").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblUsuari__Escol__49C3F6B7", "tblEscola").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Escola> EscolaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblUsuari__Escol__49C3F6B7", "tblEscola");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Escola>("EnglishSchoolManagerModel.FK__tblUsuari__Escol__49C3F6B7", "tblEscola", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EnglishSchoolManagerModel", "FK__tblPagame__Aluno__49C3F6B7", "tblPagamento")]
        public EntityCollection<Pagamento> Pagamentos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Pagamento>("EnglishSchoolManagerModel.FK__tblPagame__Aluno__49C3F6B7", "tblPagamento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Pagamento>("EnglishSchoolManagerModel.FK__tblPagame__Aluno__49C3F6B7", "tblPagamento", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
